### ISSUE TITLE
Configuration option to disable "Conversation Subject"

### ISSUE THREAD

**Issue by mccrodp** [FriendsOfSymfony/FOSMessage#27]
From playing around with the demo I noticed "Conversation Subject". In the cases where someone might want to reproduce a system like the Facebook Messenger; i.e. - no conversation subject, is it possible to bundle messages by recipient rather than Conversation Subject?

i.e. - Is it possible to easily remove Conversation Subject and have Conversations based on receipients without changing so much code?

**Comment by tgalopin** [comment]
Hello :) !

The subject is fully optionnal in FOSMessage: you can easily disable it just by not providing it. A quite simple way to implement a "participants based" conversation system is to create a conversation between users the first time they talk together and then reuse this conversation object instead of creating a new one. It's not complicated, but if I'm not clear, don't hesitate to ask :) !

**Comment by mccrodp** [comment]
Hey @tgalopin! Thanks for the fast response again.

That sounds great, I just wanted to double check that it was easily configurable. 

I haven't had a chance to look that closely at the code yet, more so at the driver so far. Ideally I'd like to make that Subject optional for any users of a Drupal module. So I guess I'd need some logic to switch between participants based and subject based conversation system. Where is the best home for this kind of logic?

**Comment by tgalopin** [comment]
I guess this should be an option in your module, and using this option, you should be able in your controller to either create a new conversation (with a subject or not) or load the existing one.

**Comment by mccrodp** [comment]
Awesome, that makes sense. Thanks.
